### ISSUE TITLE
Type exit to exit is not exit actually

### ISSUE THREAD

**Issue by rajcybage** [thoughtbot/gitsh#239]
````
rajarshi@rajarshi-X200CA:~/kit$ gitsh
gitsh 0.9
Type :exit to exit
kit facebook! exit
git: 'exit' is not a git command. See 'git --help'.

Did you mean this?
	init
kit facebook!
`````

I am new on gitsh but exit is not working.

**Comment by georgebrock** [comment]
You need to use the `:` prefix: `:exit` instead of `exit`. You can also exit by sending an EOF character (<kbd><kbd>ctrl</kbd>+<kbd>d</kbd></kbd>)

The colon prefix is there to distinguish gitsh commands, that tell the shell to do something, from Git commands, that perform version control tasks. We didn't want to assume that users wouldn't already have Git aliases with names like `set` and `exit` that would conflict with the gitsh commands.

The manual page (`man gitsh` from your regular Unix shell) is a good source of information on how to use gitsh.

Hope that helps.

**Comment by rajcybage** [comment]
Thanks you @georgebrock
