### ISSUE TITLE
Support pipelines

### ISSUE THREAD

**Issue by calleerlandsson** [thoughtbot/gitsh#263]
Sometimes, I want to execute a shell command from within gitsh and the `!` prefix makes this very convenient. Sometimes, the shell command I want to execute includes a pipeline and when I try executing it with `!` it fails with a parse error:

```
pick master@ !git log | wc -l
gitsh: parse error
```

I've read the man page, the README and the parser code but can't figure out if there's a way to execute a pipeline.

If there isn't, would you be interested in supporting this? If so, I'd be happy to take a stab at implementing it. Do you have any pointers for how to best approach implementing this?

**Comment by georgebrock** [comment]
It's not currently possible to use any kind of pipeline in gitsh.

I'd definitely be interested in supporting this, but I think we should look at the possibility of gitsh natively supporting pipelines rather than leaning on an external shell for them. That'd allow for pipelines that mix Git commands, gitsh commands, and shell commands. You example would probably be re-written as:

```
pick master@ log | !wc -l
```

The parser already supports the `||`, `&&`, and `;` operators to join multiple commands together, which the transformer turns into the relevant subclass of `Gitsh::Commands::Tree::Branch`, depending on the operator. We could probably use a similar structure could be used to support the `|` operator, perhaps producing a `Gitsh::Commands::Pipeline` object which could do something with `IO.pipe` and `Process.spawn` to connect up the pipeline.

What do you think?

**Comment by georgebrock** [comment]
Closing in favour of #299.
