### ISSUE TITLE
Quoting and subcommands

### ISSUE THREAD

**Issue by sharplet** [thoughtbot/gitsh#328]
Here's the command I was trying to execute (essentially, pluck `feature-branch` from wherever it branched off `master`, and rebase it onto `new-base`), and the unexpected error message:

```
@ rebase --onto new-base $(merge-base master feature-branch) feature-branch
fatal: Needed a single revision
invalid upstream 'f1c4e38a3240741ce4cbc5f25b8c53c0a6cad6fafeature-branch'
```

This invocation succeeded:

```
@ rebase --onto new-base "$(merge-base master feature-branch)" feature-branch
```

Is this expected behaviour?

**Comment by georgebrock** [comment]
A simpler example to reproduce this:

```
:echo foo $(rev-parse HEAD) bar
```

Expected output:

```
foo f3b965188abd09aa0694270afbb69f8a0200a198 bar
```

Actual output:

```
foo f3b965188abd09aa0694270afbb69f8a0200a198bar
```

Looks like the root of this issue is in the lexer: the `RIGHT_PAREN` and `SUBSHELL_END` tokens use the regular expression `/\s*\)\s*/`. In other words, any whitespace following the `)` is taken as part of the `)` token.

The current implementation is nice because it handles pretty much all the whitespace at the lexer level, and the parser doesn't need to be peppered with “there might be whitespace here” annotations, but maybe we'll have to go down that road to resolve this issue.
