### ISSUE TITLE
:cd command should also change dir of parent shell

### ISSUE THREAD

**Issue by chris-perts** [thoughtbot/gitsh#373]
A feature request. I have all my repos in a common parent directory, so I often switch between them with `:cd ../newRepo`. Current behavior:

```
laptop:myRepo chris$ gitsh
myRepo master@ :cd ../newRepo
newRepo master@ :exit
laptop:myRepo chris$ echo "now I am confused"
```

This always breaks my brain. Upon exiting, I am yanked back to the directory I was in when I entered gitsh. For some reason I consistently expect this:

```
laptop:myRepo chris$ gitsh
myRepo master@ :cd ../newRepo
newRepo master@ :exit
laptop:newRepo chris$ echo "sweet consistency"
```

**Comment by georgebrock** [comment]
Thanks for the suggestion. I don't plan to make this change for a couple of reasons.

First, I'm not sure this is possible: I'm not aware of any mechanism that would allow a child process to change its parent process' working directory. A quick web search is only turning up approaches that either only work in specific context (e.g. it might be possible to do this if we know the parent process was always GNU Bash) or rely on mechanisms that aren't appropriate for production software (e.g. using a debugger to manipulate the parent process').

Second, it's inconsistent with the behaviour of existing Unix shells. gitsh attempts to follow patterns established by existing general purpose shells wherever possible, and making this change would go against that design philosophy. For example, here's what happens if I run the zsh shell from a Bash shell, change directory, and then quit. I've prefixed the prompts to read `bash` and `zsh` for clarity:

```
(bash) hailstone ~$ pwd
/Users/georgebrock
(bash) hailstone ~$ zsh
(zsh) georgebrock@hailstone ~ % cd code/gitsh
(zsh) georgebrock@hailstone gitsh % pwd
/Users/georgebrock/code/gitsh
(zsh) georgebrock@hailstone gitsh % exit
(bash) hailstone ~$ pwd
/Users/georgebrock
```

**Comment by chris-perts** [comment]
Fair enough. I appreciate the thought you put into this. Cheers!
